---
name: apps deployment
on:
  workflow_dispatch:
    inputs:
      name:
        description: "target environment name"
        required: true
jobs:
  deploy_source:
    name: apps
    runs-on: ubuntu-latest
    env:
      CN: dev
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 773342935443.dkr.ecr.eu-central-1.amazonaws.com/devops-cluster-dev:latest
      - name: kubernetes credentials download
        run: aws eks --region eu-central-1 update-kubeconfig --name devops-cluster-dev
      - uses: azure/setup-kubectl@v1
        with:
          version: latest
        id: install
      - name: apply
        run: kubectl apply -f kubes.yml
      - name: pods and services
        run: kubectl get pod,svc
      - name: apply
        run: kubectl delete	t2.medium	
2/2 checks passed	
No alarms
eu-central-1b	–	–	–	–	disabled	eks-remoteAccess-94be6af7-a9db-4508-d00c-0fcec90d3ff3,eks-cluster-sg-devops-cluster-dev-1755188622	vanguard	2021/10/31 16:12 GMT+5:30 -f kubes.yml
